name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build-test:
    if: ${{ hashFiles('**/*.xcodeproj','**/*.xcworkspace') != '' }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"
      - name: Resolve SPM
        run: xcodebuild -resolvePackageDependencies -scheme "CoWorkerAI"
      - name: Build (macOS)
        run: xcodebuild -scheme "CoWorkerAI" -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO

  no-project-yet:
    if: ${{ hashFiles('**/*.xcodeproj','**/*.xcworkspace') == '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "No Xcode project yet; skipping CI."
