name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build & Test (only when Xcode project exists)
    if: ${{ hashFiles('**/*.xcodeproj','**/*.xcworkspace') != '' }}
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5
      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"
      - name: Resolve SPM
        run: xcodebuild -resolvePackageDependencies -scheme "CoWorkerAI"
      - name: Build
        run: xcodebuild -scheme "CoWorkerAI" -destination 'platform=iOS Simulator,name=iPhone 15'
      - name: Test
        run: xcodebuild test -scheme "CoWorkerAI" -destination 'platform=iOS Simulator,name=iPhone 15'

  template-ok:
    if: ${{ hashFiles('**/*.xcodeproj','**/*.xcworkspace') == '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "No Xcode project yet; skipping CI in template (expected)."
