name: Foundation Guard
on:
  pull_request:
    branches: [ main ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run foundation health check
        run: bash scripts/foundation-health.sh
